# Generated by Django 4.1.2 on 2022-10-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='persone',
            name='imei',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Trafic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, 'chats'), (2, 'voice_chats'), (3, 'video'), (4, 'audio'), (5, 'files'), (6, 'email')], null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('persone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.persone')),
            ],
        ),
        migrations.AddField(
            model_name='persone',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.group'),
        ),
        migrations.AddField(
            model_name='persone',
            name='interfaces',
            field=models.ManyToManyField(to='general.interface'),
        ),
    ]
