# Generated by Django 4.1.2 on 2022-10-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_group_interface_persone_imei_trafic_persone_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCAPFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='get_upload_to')),
                ('persone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.persone')),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='get_upload_to')),
                ('persone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.persone')),
            ],
        ),
    ]
