# Generated by Django 4.1.2 on 2022-10-22 18:48

from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_pcapfile_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=general.models.get_csv_upload_to),
        ),
        migrations.AlterField(
            model_name='pcapfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=general.models.get_pcap_upload_to),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('csv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.csvfile')),
                ('pcaps', models.ManyToManyField(to='general.pcapfile')),
                ('persone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.persone')),
            ],
        ),
    ]
