# Generated by Django 4.1.2 on 2022-10-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_trafic_end_remove_trafic_start_trafic_ask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafic',
            name='persone',
        ),
        migrations.AddField(
            model_name='trafic',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.package'),
        ),
    ]
