# Generated by Django 4.1.2 on 2022-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_trafic_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafic',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
