# Generated by Django 4.1.2 on 2022-10-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_trafic_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafic',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
