# Generated by Django 4.1.2 on 2022-10-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_alter_trafic_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafic',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'chats'), (1, 'video'), (2, 'files'), (3, 'email'), (4, 'sftp'), (5, 'ftps')], null=True),
        ),
    ]
